# Generated by Django 4.2 on 2023-05-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_userlikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
