# Generated by Django 4.2 on 2023-06-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_posts_comment_alter_userlikes_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=100000)),
            ],
        ),
    ]
